### ISSUE TITLE
大佬好，能抽空解答一下吗，先谢谢啦。

### ISSUE THREAD

**Issue by wubantudl** [potats0/cve_2020_14644#2]
Exception in thread "main" javax.naming.NameNotFoundException: Exception in look
up.: `UnicodeSec' could not be found. [Root exception is weblogic.corba.cos.nami
ng.NamingContextAnyPackage.NotFound: IDL:weblogic/corba/cos/naming/NamingContext
Any/NotFound:1.0]
        at weblogic.corba.j2ee.naming.Utils.wrapNamingException(Utils.java:65)
        at weblogic.corba.j2ee.naming.ContextImpl.lookup(ContextImpl.java:289)
        at weblogic.corba.j2ee.naming.ContextImpl.lookup(ContextImpl.java:227)
        at org.unicodesec.App.main(App.java:37)
Caused by: weblogic.corba.cos.naming.NamingContextAnyPackage.NotFound: IDL:weblo
gic/corba/cos/naming/NamingContextAny/NotFound:1.0
        at weblogic.corba.cos.naming.NamingContextAnyPackage.NotFoundHelper.read
(NotFoundHelper.java:72)
        at weblogic.corba.cos.naming._NamingContextAnyStub.resolve_any(_NamingCo
ntextAnyStub.java:87)
        at weblogic.corba.cos.naming._NamingContextAnyStub.resolve_any(_NamingCo
ntextAnyStub.java:95)
        at weblogic.corba.j2ee.naming.ContextImpl.lookup(ContextImpl.java:267)
        ... 2 more

**Comment by wubantudl** [comment]
谢谢，强烈推荐公众号
宽字节安全

**Comment by potats0** [comment]
已经更新代码了，jar包也更新了

**Comment by wubantudl** [comment]
今早已经看到了，辛苦辣
